spring:
  application:
    name: IndexHomeSharer
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/indexsharer
    username: root
    password: 123456
  ai:
    openai:
      api-key: sk-qYvVzOAOo5nawGlfFb74652e697940Ac83D47b57D0E5D549
      base-url: https://oneai.evanora.top
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

server:
  port: 8000
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
homeindexsharer:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret: indexsharer
    # 设置jwt过期时间
    expiration: ????
    # 设置前端传递过来的令牌名称
    tokenName: token
  alioss:
    endpoint: ????
    access-key-id: ????
    access-key-secret: ????
    bucket-name: ????
