spring:
  application:
    name: IndexHomeSharer
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/indexsharer
    username: root
    password: 123456
server:
  port: 8000
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
